[2013-12-24 16:48:04,724 - autoapi error info]ERROR:  string indices must be integers - resolve_xml.py:107
[2013-12-24 16:48:49,180 - autoapi error info]ERROR:  string indices must be integers - resolve_xml.py:107
[2013-12-24 16:49:24,748 - autoapi error info]ERROR:  string indices must be integers - resolve_xml.py:106
[2013-12-24 16:49:44,571 - autoapi error info]ERROR:  string indices must be integers - resolve_xml.py:107
[2013-12-24 16:50:38,559 - autoapi error info]ERROR:  string indices must be integers - resolve_xml.py:107
[2013-12-24 16:50:51,159 - autoapi error info]ERROR:  string indices must be integers - resolve_xml.py:107
[2013-12-24 16:51:24,439 - autoapi error info]ERROR:  string indices must be integers - resolve_xml.py:107
[2013-12-24 16:53:48,527 - autoapi error info]ERROR:  string indices must be integers - resolve_xml.py:107
[2013-12-24 16:55:34,816 - autoapi error info]ERROR:  string indices must be integers - resolve_xml.py:107
[2013-12-24 16:56:02,136 - autoapi error info]ERROR:  string indices must be integers - resolve_xml.py:108
[2013-12-24 16:56:56,616 - autoapi error info]ERROR:  'pic_urls' - resolve_xml.py:109
[2013-12-25 15:36:07,265 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:23
[2013-12-25 15:39:45,093 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:23
[2013-12-25 16:10:06,456 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:23
[2013-12-25 16:10:36,011 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:23
[2013-12-25 17:18:40,285 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:23
[2013-12-25 17:51:46,538 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:25
[2013-12-25 17:52:33,328 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:25
[2013-12-25 18:00:38,888 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:25
[2013-12-25 18:02:06,894 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:26
[2013-12-25 18:02:40,975 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:27
[2013-12-25 18:03:07,522 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:27
[2013-12-25 18:03:40,108 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:27
[2013-12-25 18:04:53,567 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:27
[2013-12-25 18:06:27,132 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:27
[2013-12-25 18:12:04,344 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:25
[2013-12-25 19:07:17,548 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:25
[2013-12-25 19:07:55,398 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:25
[2013-12-25 19:08:24,150 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:25
[2013-12-25 19:08:50,240 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:25
[2013-12-25 19:10:08,124 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:25
[2013-12-25 19:11:10,667 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:25
[2013-12-27 16:28:45,317 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:25
[2013-12-30 14:00:11,799 - autoapi error info]ERROR:  Get expect value errro. - deal_string.py:26
[2013-12-30 14:45:18,548 - autoapi error info]ERROR:  no test plan param. - run.py:64
[2014-01-02 16:27:56,512 - autoapi error info]ERROR:  no test plan param. - run.py:67
[2014-01-02 16:56:11,853 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:132
[2014-01-02 16:56:32,623 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:132
[2014-01-02 16:57:17,084 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:133
[2014-01-02 16:57:47,168 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:132
[2014-01-02 16:58:39,543 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:132
[2014-01-02 16:59:13,872 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:132
[2014-01-02 17:00:29,489 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:132
[2014-01-02 17:03:36,788 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:133
[2014-01-02 17:09:05,812 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:134
[2014-01-02 17:10:10,923 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:134
[2014-01-02 17:17:29,047 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:131
[2014-01-02 17:18:58,700 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:130
[2014-01-02 17:20:09,852 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:130
[2014-01-02 17:20:59,737 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:131
[2014-01-02 17:22:23,112 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:131
[2014-01-02 17:23:26,685 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:132
[2014-01-02 17:24:15,726 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:133
[2014-01-02 17:25:27,357 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:133
[2014-01-02 17:26:03,183 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:130
[2014-01-02 17:27:45,746 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:130
[2014-01-02 17:28:13,291 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:131
[2014-01-03 10:19:21,558 - autoapi error info]ERROR:  list index out of range - run.py:96
[2014-01-03 11:21:06,457 - autoapi error info]ERROR:  [Errno 2] No such file or directory: 'zeyang.pla' - resolve_xml.py:126
[2014-01-03 11:43:10,267 - autoapi error info]ERROR:  list index out of range - run.py:96
[2014-01-03 13:25:50,337 - autoapi error info]ERROR:  list index out of range - run.py:90
[2014-01-03 13:39:29,396 - autoapi error info]ERROR:  invalid syntax (<string>, line 1) - resolve_xml.py:126
[2014-01-03 13:49:20,007 - autoapi error info]ERROR:  'NodeList' object has no attribute 'childNodes' - resolve_xml.py:131
[2014-01-03 13:50:38,495 - autoapi error info]ERROR:  'NodeList' object has no attribute 'childNodes' - resolve_xml.py:131
[2014-01-03 13:51:37,211 - autoapi error info]ERROR:  'NodeList' object has no attribute 'childNodes' - resolve_xml.py:132
[2014-01-03 13:52:05,427 - autoapi error info]ERROR:  'NodeList' object has no attribute 'childNodes' - resolve_xml.py:133
[2014-01-03 13:53:20,955 - autoapi error info]ERROR:  'NodeList' object has no attribute 'childNodes' - resolve_xml.py:134
[2014-01-03 14:15:15,341 - autoapi error info]ERROR:  [Errno 2] No such file or directory: u'(.api.xml' - resolve_xml.py:131
[2014-01-03 14:15:15,341 - autoapi error info]ERROR:  [Errno 2] No such file or directory: u'(.case.xml' - resolve_xml.py:131
[2014-01-03 14:16:00,055 - autoapi error info]ERROR:  [Errno 2] No such file or directory: u'(.api.xml' - resolve_xml.py:131
[2014-01-03 14:16:00,055 - autoapi error info]ERROR:  [Errno 2] No such file or directory: u'(.case.xml' - resolve_xml.py:131
[2014-01-03 14:16:21,652 - autoapi error info]ERROR:  [Errno 2] No such file or directory: u'(.api.xml' - resolve_xml.py:131
[2014-01-03 14:16:21,652 - autoapi error info]ERROR:  [Errno 2] No such file or directory: u'(.case.xml' - resolve_xml.py:131
[2014-01-03 14:16:54,004 - autoapi error info]ERROR:  [Errno 2] No such file or directory: u'(.api.xml' - resolve_xml.py:131
[2014-01-03 14:16:54,004 - autoapi error info]ERROR:  [Errno 2] No such file or directory: u'(.case.xml' - resolve_xml.py:131
[2014-01-03 14:18:44,735 - autoapi error info]ERROR:  [Errno 2] No such file or directory: u'(.api.xml' - resolve_xml.py:131
[2014-01-03 14:18:44,735 - autoapi error info]ERROR:  [Errno 2] No such file or directory: u'(.case.xml' - resolve_xml.py:131
[2014-01-03 14:18:57,585 - autoapi error info]ERROR:  [Errno 2] No such file or directory: u'(.api.xml' - resolve_xml.py:131
[2014-01-03 14:18:57,585 - autoapi error info]ERROR:  [Errno 2] No such file or directory: u'(.case.xml' - resolve_xml.py:131
[2014-01-03 14:19:22,082 - autoapi error info]ERROR:  [Errno 2] No such file or directory: u'i.api.xml' - resolve_xml.py:131
[2014-01-03 14:19:22,082 - autoapi error info]ERROR:  [Errno 2] No such file or directory: u'i.case.xml' - resolve_xml.py:131
[2014-01-03 14:33:02,459 - autoapi error info]ERROR:  [Errno 2] No such file or directory: 'queryid.case.xml' - resolve_xml.py:131
[2014-01-03 14:34:18,088 - autoapi error info]ERROR:  [Errno 2] No such file or directory: 'queryid.case.xml' - resolve_xml.py:131
[2014-01-03 14:34:44,316 - autoapi error info]ERROR:  [Errno 2] No such file or directory: 'queryid.case.xml' - resolve_xml.py:131
[2014-01-03 14:38:55,101 - autoapi error info]ERROR:  [Errno 2] No such file or directory: 'queryid.case.xml' - resolve_xml.py:131
[2014-01-03 14:39:53,341 - autoapi error info]ERROR:  [Errno 2] No such file or directory: 'queryid.case.xml' - resolve_xml.py:131
[2014-01-03 14:40:44,781 - autoapi error info]ERROR:  [Errno 2] No such file or directory: 'queryid.case.xml' - resolve_xml.py:132
[2014-01-03 14:42:05,884 - autoapi error info]ERROR:  [Errno 2] No such file or directory: 'queryid.case.xml' - resolve_xml.py:132
[2014-01-03 14:42:26,346 - autoapi error info]ERROR:  [Errno 2] No such file or directory: 'queryid.case.xml' - resolve_xml.py:131
[2014-01-03 14:43:14,968 - autoapi error info]ERROR:  [Errno 2] No such file or directory: 'queryid.case.xml' - resolve_xml.py:131
